# Generated by Django 4.1.4 on 2022-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20)),
                ('first_menu_name', models.CharField(max_length=20)),
                ('first_menu_image', models.ImageField(upload_to='images/')),
                ('contents', models.CharField(blank=True, max_length=100)),
                ('naver_map_URL', models.URLField()),
                ('favorite', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=70)),
            ],
        ),
    ]
